"""create messages table

Revision ID: 9f1a67de4d8f
Revises: d67ff93dde6e
Create Date: 2025-01-28 21:52:07.132818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1a67de4d8f'
down_revision = 'd67ff93dde6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
