"""Add Message model

Revision ID: d67ff93dde6e
Revises: 0a3a911b63ae
Create Date: 2025-01-28 21:46:53.554748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67ff93dde6e'
down_revision = '0a3a911b63ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
